# DOCKERFILE PASSWORDAPI

# Importo la imagen base
FROM fabric8/java-alpine-openjdk8-jdk
# Defino directorio de trabajo
WORKDIR /deployments/
# Copio aplicación a la imagen
COPY passwordapi.jar app.jar
# Expongo puerto
EXPOSE 8080
